# application-docker.yml (или используйте переменные окружения)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/school_analysis}
    username: ${SPRING_DATASOURCE_USERNAME:school_user}
    password: ${SPRING_DATASOURCE_PASSWORD:school_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Папки в Docker контейнере
file:
  input-dir: /app/input
  output-dir: /app/output
  processed-dir: /app/processed

logging:
  level:
    org.school.analysis: DEBUG
    org.springframework.transaction: INFO


app:
  excel:
    charts:
      col-span: 10
      row-span: 15
      spacing: 5
      left-offset: 1
      fully-completed-color: "0,20,236"
      partially-completed-color: "241,120,0"
      not-completed-color: "231,50,60"
      percentage-color: "52,152,219"
      line-color: "52,152,219"
      line-width: 2.0
      marker-size: 6