version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: school-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_analysis
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:  # Опционально
    image: dpage/pgadmin4:latest
    container_name: school-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@school.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: